export * from 'pages/Home/Home';
export * from 'pages/Catalog/Catalog';
export * from 'pages/Catalog/Pages/Pet';
export * from 'pages/Catalog/Pages/Category';
export * from 'pages/Catalog/Pages/ProductType';
export * from 'pages/Brands';
export * from 'pages/AboutUs';
export * from 'pages/Cart/Cart';
export * from 'pages/ProductCard/ProductCard';
export * from 'pages/PageNotFound';
export * from 'pages/PricesDrop';
export * from 'pages/Contacts';
export * from 'pages/PageUnderConstruction';
export * from 'pages/Registration/Registration';
export * from 'pages/UserPage/UserPage';
export * from 'pages/CreateNewPass/CreateNewPass'
